import 'package:flutter/material.dart';
import 'package:inkpadu/features/ink/presentation/drawing_note/widgets/drawing_canvas.dart'
    show AiBoundingBox;

/// A widget layer that handles rendering the lasso selection overlay.
class LassoSelectionLayer extends StatelessWidget {
  /// Creates a [LassoSelectionLayer].
  const LassoSelectionLayer({
    super.key,
    required this.lassoPoints,
    required this.selectedStrokeBounds,
    required this.aiBoundingBoxes,
    required this.selectionColor,
    required this.lassoColor,
    required this.isCapturingForAi,
  });

  /// Current points of the drawn lasso.
  final List<Offset> lassoPoints;

  /// Bounds of the currently selected strokes.
  final List<Rect> selectedStrokeBounds;

  /// Bounding boxes generated by the AI panel.
  final List<AiBoundingBox> aiBoundingBoxes;

  /// The color of the selection highlight.
  final Color selectionColor;

  /// The color of the drawn lasso path.
  final Color lassoColor;

  /// Whether an AI capture is currently in progress (hides the layer if true).
  final bool isCapturingForAi;

  @override
  Widget build(BuildContext context) {
    if (isCapturingForAi) return const SizedBox.shrink();

    return RepaintBoundary(
      child: CustomPaint(
        painter: LassoSelectionPainter(
          lassoPoints: lassoPoints,
          selectedStrokeBounds: selectedStrokeBounds,
          aiBoundingBoxes: aiBoundingBoxes,
          selectionColor: selectionColor,
          lassoColor: lassoColor,
        ),
      ),
    );
  }
}

/// A custom painter to draw the lasso path and selected bounds.
class LassoSelectionPainter extends CustomPainter {
  /// Creates a [LassoSelectionPainter].
  LassoSelectionPainter({
    required List<Offset> lassoPoints,
    required List<Rect> selectedStrokeBounds,
    required List<AiBoundingBox> aiBoundingBoxes,
    required this.selectionColor,
    required this.lassoColor,
  }) : lassoPoints = List<Offset>.unmodifiable(lassoPoints),
       selectedStrokeBounds = List<Rect>.unmodifiable(selectedStrokeBounds),
       aiBoundingBoxes = List<AiBoundingBox>.unmodifiable(aiBoundingBoxes);

  /// Current points of the drawn lasso.
  final List<Offset> lassoPoints;

  /// Bounds of the currently selected strokes.
  final List<Rect> selectedStrokeBounds;

  /// Bounding boxes generated by the AI panel.
  final List<AiBoundingBox> aiBoundingBoxes;

  /// The color of the selection highlight.
  final Color selectionColor;

  /// The color of the drawn lasso path.
  final Color lassoColor;

  @override
  void paint(Canvas canvas, Size size) {
    if (selectedStrokeBounds.isNotEmpty) {
      final paint = Paint()
        ..color = selectionColor.withValues(alpha: 0.55)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 2;

      double minX = double.infinity;
      double minY = double.infinity;
      double maxX = double.negativeInfinity;
      double maxY = double.negativeInfinity;

      for (final rect in selectedStrokeBounds) {
        if (rect.left < minX) minX = rect.left;
        if (rect.top < minY) minY = rect.top;
        if (rect.right > maxX) maxX = rect.right;
        if (rect.bottom > maxY) maxY = rect.bottom;
      }

      if (minX != double.infinity) {
        final combinedRect = Rect.fromLTRB(minX, minY, maxX, maxY);
        final rrect = RRect.fromRectAndRadius(
          combinedRect.inflate(6),
          const Radius.circular(10),
        );
        canvas.drawRRect(rrect, paint);
      }
    }

    if (aiBoundingBoxes.isNotEmpty) {
      for (final aiBox in aiBoundingBoxes) {
        final paint = Paint()
          ..color = aiBox.color.withValues(alpha: 0.4)
          ..style = PaintingStyle.fill;
        final rrect = RRect.fromRectAndRadius(
          aiBox.rect.inflate(4),
          const Radius.circular(8),
        );
        canvas.drawRRect(rrect, paint);
      }
    }

    if (lassoPoints.length >= 2) {
      final paint = Paint()
        ..color = lassoColor.withValues(alpha: 0.75)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 2;
      final path = Path()..moveTo(lassoPoints.first.dx, lassoPoints.first.dy);
      for (final p in lassoPoints.skip(1)) {
        path.lineTo(p.dx, p.dy);
      }
      canvas.drawPath(path, paint);
    }
  }

  @override
  bool shouldRepaint(covariant LassoSelectionPainter oldDelegate) =>
      oldDelegate.lassoPoints != lassoPoints ||
      oldDelegate.selectedStrokeBounds != selectedStrokeBounds ||
      oldDelegate.aiBoundingBoxes != aiBoundingBoxes ||
      oldDelegate.selectionColor != selectionColor ||
      oldDelegate.lassoColor != lassoColor;
}
